# Generated by Django 2.1 on 2018-08-23 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180823_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 23, 18, 21, 55, 826389), verbose_name='添加时间'),
        ),
    ]
