# Generated by Django 2.0.7 on 2018-08-23 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180823_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 23, 20, 57, 12, 453308), verbose_name='添加时间'),
        ),
    ]
